management:
  port: 8081 # 管理端口 spring-boot-starter-acturator
spring: 
  application:
    name: hystrix-consumer3
server: 
  port: 9010 # 访问端口
eureka: 
  client: 
    service-url: 
        defaultZone: http://localhost:8761/eureka/
  instance: 
    prefer-ip-address: false
    metadata-map:
      management.port: ${management.port}
# 防止第一次访问超时，默认1秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
    