spring: 
  application:
    name: gateway-zuul-file-upload
  http:
    multipart:
      max-file-size: 2000Mb     # 默认1M
      max-request-size: 2500Mb  # 默认10M  
server: 
    port: 10010
    
#eureka: 
##  client: 
##    serviceUrl: 
##      defaultZone: http://localhost:8761/eureka/
#  instance: 
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
 
#zuul:
#  routes:
#  # 配置的路由使用/test/**
#    test-service-v1: 
#      path: /test/**
#  # 剩下的使用/**
#    legacy: 
#      path: /**
      
logging:
  level:
    com.netflix: DEBUG