spring: 
  application:
    name: hystrix-consumer2
    
server: 
  port: 9010
  context-path: /ribbon
  
eureka: 
  client: 
    service-url: 
        defaultZone: http://localhost:8761/eureka/
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.application.name}.${spring.cloud.client.ipAddress}.${server.port} 
# 防止context-path无法访问，使用home-page-url后，homePageUrl变成 http://ip:port/ribbon
    home-page-url: /ribbon  

# 防止第一次访问超时，默认1秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
    