spring: 
  application:
    name: eureka-server
    
server: 
    port: 8095
eureka: 
  instance: 
    hostname: peer1
  client: 
    serviceUrl: 
      defaultZone: http://peer2:8096/eureka/,http://peer3:8097/eureka/
    
---
server: 
    port: 8097
eureka: 
  instance: 
    hostname: peer3
  client: 
    serviceUrl: 
      defaultZone: http://peer1:8095/eureka/,http://peer2:8096/eureka/

---
server: 
    port: 8096
eureka: 
  instance: 
    hostname: peer2
  client: 
    serviceUrl: 
      defaultZone: http://peer1:8095/eureka/,http://peer3:8097/eureka/
  server: 
    enable-self-preservation: false # 关闭注册中心自我保护机制
    eviction-interval-timer-in-ms: 5000 # 注册中心清理间隔（单位：毫秒，默认 60*1000）