#如果配置了server.servlet-path = /Demo，访问路径就是http://ip:port/Demo/...
#不配置或server.servlet-path = /，访问路径就是http://ip:port/... 
# server.context-path=/test
spring: 
  application:
     name: dev-service
server: 
  port: 8082
#  servlet-path: /test

#spring: 
#  datasource: 
#    driver-class-name: 
#    url: 
#    username: 
#    password: 


# 日志输出文件级别
logging:
#  path: classpath:E:/java/workspace-cloud/test-springboot-1/src/main/resources/static/logs
  file: devLog
  level:
    root: info

eureka: 
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://peer1:8095/eureka/,http://peer2:8096/eureka/,http://peer3:8097/eureka/
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.application.name}.${spring.cloud.client.ipAddress}.${server.port}