spring: 
  application:
    name: feign-consumer-service-without-hystrix
    
server: 
  port: 9005
  
eureka: 
  client: 
    service-url: 
        defaultZone: http://localhost:8761/eureka/
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port} 

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

feign:
  hystrix: 
    enabled: true