server:
  port: 9011
  context-path: /ribbon
  
spring:
  application:
    name: hystrix-consumer-turbine2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    home-page-url-path: /ribbon  # 保证url正常使用，不需要输入context-path
    
turbine:
  aggregator: 
    clusterConfig: HYSTRIX-CONSUMER2
  appConfig: hystrix-consumer2

turbine.instanceUrlSuffix.HYSTRIX-CONSUMER-TEST-TURBINE: /ribbon/hystrix.stream

logging:
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG
  