server:
  port: 9011
  
spring:
  application:
    name: hystrix-consumer-turbine3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    
turbine:
  aggregator:
# 指定聚合那些集群，多个使用","分割，默认为default。可使用 
# http://.../turbine.stream?cluster={clusterConfig之一}访问
    clusterConfig: HYSTRIX-CONSUMER3

# 配置eureka中的serviceId列表，表明要监控的微服务集群  
  appConfig: hystrix-consumer3
  
#turbine.instanceUrlSuffix.HYSTRIX-CONSUMER-TEST-TURBINE: /ribbon/hystrix.stream  
  