
#如果配置了server.servlet-path = /Demo，访问路径就是http://ip:port/Demo/...
#不配置或server.servlet-path = /，访问路径就是http://ip:port/... 
# server.context-path=/test

server:
  port: 8083
#  servlet-path: /pro

spring: 
  application:
     name: pro-service
     
#eureka: 
#  client: 
#    register-with-eureka: true
#    fetch-registry: true
#    service-url: 
#      defaultZone: http://peer1:8095/eureka/,http://peer2:8096/eureka/,http://peer3:8097/eureka/
#  instance: 
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}.${spring.cloud.client.ipAddress}.${server.port}
#    