spring: 
  application:
    name: feign-consumer-service-with-hystrix
    
server: 
  port: 9003
  
eureka: 
  client: 
    service-url: 
        defaultZone: http://localhost:8761/eureka/
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port} 
    
feign:
  hystrix: 
    enabled: true
